title: SRI Reference Knowledge Graph API
version: 2.0.0
contact:
  email: kevin@tislab.org
  name: Kevin Schaper
  x-id: https://github.com/kevinschaper
  x-role: responsible developer
license:
  name: License To Be Determined
  url: TBD
termsOfService: https://monarchinitiative.org/about/licensing
x-translator:
  component: KP
  team:
    - Standards Reference Implementation Team
  biolink-version:
x-trapi:
  version: 1.2.0
x-type: api documentation
servers:
- description: Default server
  url: https://trapi.monarchinitiative.org/1.2
tags:
- name: translator
- name: trapi
